import { Niche, EquipmentCatalog, NicheRequirement } from './types'

export const mockNiches: Niche[] = [
  {
    id: '1',
    name: 'Портретная фотография',
    slug: 'portrait',
    icon: '👤',
    description: 'Профессиональная съемка портретов и headshots',
    parent_id: null,
    sort_order: 1,
  },
  {
    id: '2',
    name: 'Пейзажная фотография',
    slug: 'landscape',
    icon: '🏔️',
    description: 'Природные и архитектурные пейзажи',
    parent_id: null,
    sort_order: 2,
  },
  {
    id: '3',
    name: 'Свадебная фотография',
    slug: 'wedding',
    icon: '💍',
    description: 'Съемка свадебных событий и церемоний',
    parent_id: null,
    sort_order: 3,
  },
  {
    id: '4',
    name: 'Предметная фотография',
    slug: 'product',
    icon: '📦',
    description: 'Съемка товаров для каталогов и e-commerce',
    parent_id: null,
    sort_order: 4,
  },
  {
    id: '5',
    name: 'Спортивная фотография',
    slug: 'sports',
    icon: '⚽',
    description: 'Съемка спортивных событий и соревнований',
    parent_id: null,
    sort_order: 5,
  },
  {
    id: '6',
    name: 'Видеография',
    slug: 'video',
    icon: '🎬',
    description: 'Профессиональная видеосъемка и видеомонтаж',
    parent_id: null,
    sort_order: 6,
  },
]

export const mockEquipmentCatalog: EquipmentCatalog[] = [
  {
    id: '1',
    name: 'Canon EOS R5',
    brand: 'Canon',
    category: 'Camera',
    subcategory: 'DSLR',
    description: 'Профессиональная зеркальная камера с полнокадровой матрицей',
    price_min: 3500,
    price_max: 4000,
    image_url: null,
    specs: { resolution: '45MP', sensor: 'Full Frame', iso: '100-102400' },
  },
  {
    id: '2',
    name: 'Sony A7R V',
    brand: 'Sony',
    category: 'Camera',
    subcategory: 'Mirrorless',
    description: 'Высокоразрешающая беззеркальная камера',
    price_min: 3980,
    price_max: 4500,
    image_url: null,
    specs: { resolution: '61MP', sensor: 'Full Frame', iso: '100-102400' },
  },
  {
    id: '3',
    name: 'Tamron 70-180mm f/2.8',
    brand: 'Tamron',
    category: 'Lens',
    subcategory: 'Telephoto',
    description: 'Универсальный телеобъектив с постоянной диафрагмой',
    price_min: 1000,
    price_max: 1200,
    image_url: null,
    specs: { focal_length: '70-180mm', aperture: 'f/2.8', weight: '1050g' },
  },
  {
    id: '4',
    name: 'Sigma 35mm f/1.4 Art',
    brand: 'Sigma',
    category: 'Lens',
    subcategory: 'Prime',
    description: 'Высокачественный портретный объектив',
    price_min: 700,
    price_max: 850,
    image_url: null,
    specs: { focal_length: '35mm', aperture: 'f/1.4', weight: '665g' },
  },
  {
    id: '5',
    name: 'Profoto B10 Plus',
    brand: 'Profoto',
    category: 'Lighting',
    subcategory: 'Flash',
    description: 'Портативная студийная вспышка',
    price_min: 3400,
    price_max: 3800,
    image_url: null,
    specs: { power: '500Ws', recycle_time: '0.05s', battery: 'Built-in' },
  },
  {
    id: '6',
    name: 'Manfrotto Befree Live',
    brand: 'Manfrotto',
    category: 'Support',
    subcategory: 'Tripod',
    description: 'Легкий алюминиевый штатив с жидкостной головой',
    price_min: 350,
    price_max: 420,
    image_url: null,
    specs: { max_height: '173cm', max_load: '8kg', weight: '1.6kg' },
  },
  {
    id: '7',
    name: 'SanDisk Extreme Pro CFast 2.0',
    brand: 'SanDisk',
    category: 'Storage',
    subcategory: 'Card',
    description: 'Высокоскоростная карта памяти для видео 4K',
    price_min: 100,
    price_max: 150,
    image_url: null,
    specs: { capacity: '64GB', speed: '525MB/s', write: '450MB/s' },
  },
  {
    id: '8',
    name: 'DJI Ronin 4D',
    brand: 'DJI',
    category: 'Support',
    subcategory: 'Gimbal',
    description: 'Профессиональный стабилизатор с камерой',
    price_min: 6000,
    price_max: 7000,
    image_url: null,
    specs: { payload: '4.3kg', runtime: '15min', resolution: '6K' },
  },
]

export const mockNicheRequirements: NicheRequirement[] = [
  {
    id: '1',
    niche_id: '1',
    category: 'Camera',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 10,
    reason: 'Основной инструмент для портретной съемки',
  },
  {
    id: '2',
    niche_id: '1',
    category: 'Lens',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 8,
    reason: 'Качественный портретный объектив необходим',
  },
  {
    id: '3',
    niche_id: '1',
    category: 'Lighting',
    equipment_id: null,
    tier: 'pro_level',
    level_required: 'advanced',
    weight: 7,
    reason: 'Контроль освещения для профессиональных результатов',
  },
  {
    id: '4',
    niche_id: '2',
    category: 'Lens',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 9,
    reason: 'Широкоугольный объектив для пейзажей',
  },
  {
    id: '5',
    niche_id: '2',
    category: 'Support',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 8,
    reason: 'Штатив для стабильной съемки',
  },
  {
    id: '6',
    niche_id: '4',
    category: 'Lighting',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 10,
    reason: 'Освещение критично для предметной фотографии',
  },
  {
    id: '7',
    niche_id: '4',
    category: 'Camera',
    equipment_id: null,
    tier: 'must_have',
    level_required: 'beginner',
    weight: 9,
    reason: 'Качественное изображение для каталогов',
  },
]

export const mockUserProfile = {
  id: 'demo-user',
  email: 'demo@kitwise.app',
  full_name: 'Демо Пользователь',
  avatar_url: null,
  niche_id: '1',
  level: 'beginner' as const,
  setup_score: 45,
  is_business: false,
  onboarding_completed: true,
}

export const mockUserEquipment = [
  {
    id: '1',
    user_id: 'demo-user',
    equipment_id: '1',
    custom_name: null,
    category: 'Camera',
    status: 'owned' as const,
    acquired_at: '2023-01-15',
    notes: null,
  },
  {
    id: '2',
    user_id: 'demo-user',
    equipment_id: '4',
    custom_name: null,
    category: 'Lens',
    status: 'owned' as const,
    acquired_at: '2023-03-20',
    notes: null,
  },
  {
    id: '3',
    user_id: 'demo-user',
    equipment_id: '6',
    custom_name: null,
    category: 'Support',
    status: 'planned' as const,
    acquired_at: null,
    notes: 'На следующий месяц',
  },
]

export const mockRecommendations = [
  {
    id: '1',
    user_id: 'demo-user',
    equipment_id: '5',
    category: 'Lighting',
    name: 'Profoto B10 Plus',
    priority: 'high' as const,
    score: 95,
    reason: 'Необходимо для профессиональных портретных сессий',
    price_range: '$3400-3800',
    status: 'pending' as const,
    ai_generated: true,
  },
  {
    id: '2',
    user_id: 'demo-user',
    equipment_id: '3',
    category: 'Lens',
    name: 'Tamron 70-180mm f/2.8',
    priority: 'medium' as const,
    score: 78,
    reason: 'Хороший универсальный телеобъектив для портретов',
    price_range: '$1000-1200',
    status: 'pending' as const,
    ai_generated: true,
  },
  {
    id: '3',
    user_id: 'demo-user',
    equipment_id: '7',
    category: 'Storage',
    name: 'SanDisk Extreme Pro CFast 2.0',
    priority: 'low' as const,
    score: 65,
    reason: 'Улучшит быстродействие при съемке видео',
    price_range: '$100-150',
    status: 'pending' as const,
    ai_generated: false,
  },
]
